### ISSUE TITLE
Error "Class 'Twig_Extensions_Extension_Intl' not found" when viewing events overview page

### ISSUE THREAD

**Issue by floriandammeyer** [andradedev/Calendar-Events-for-October-Cms#2]
When I am trying to view the CMS page that I added the Events List Component to, I get this error

```
Class 'Twig_Extensions_Extension_Intl' not found
/vagrant/plugins/jorgeandrade/events/Plugin.php line 18
```

I checked my vendor directory, apparently the twig/extensions package has not been installed. I installed OctoberCMS via the PHP installer (https://octobercms.com/docs/console/commands#console-install-quick) on the console, so I didn't use composer and therefore there is no composer.json in the root of the project. I guess that's why the dependencies have not been installed, but how do I install them if I installed the plugin via the Backend plugin management page?

**Comment by andradedev** [comment]
hey, let me see that problem and im fix at soon as possible ok?

**Comment by andradedev** [comment]
@floriandammeyer now is already fixed the problem, please try to reinstallig the plugin for install composer dependencies,and everything done

**Comment by floriandammeyer** [comment]
It's working again now, thanks very much!
